repos:
# General pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-docstring-first

# Black - code formatter
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

# Flake8 - analyses and lints the code
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8

# Bandit - find security issues in code
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit

# Isort - sort and organizes imports
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

# PyCLN - finds and removes unused imports
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln

# PyUpgrade - upgrade syntax for newer versions
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
