set shell := ["cmd.exe", "/c"]

clear-venv:
    rm -r venv

build-venv:
    python -m venv venv
    pip install -r requirements.dev.txt

server:
    venv\Scripts\activate && python server.py

proto:
    python -m grpc_tools.protoc -I../user --python_out=. --pyi_out=. --grpc_python_out=. user.proto