# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import plotter_pb2 as plotter__pb2


class PlotterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePlot = channel.unary_unary(
                '/plotter.PlotterService/GeneratePlot',
                request_serializer=plotter__pb2.PlotRequest.SerializeToString,
                response_deserializer=plotter__pb2.PlotResponse.FromString,
                )


class PlotterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeneratePlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlotterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePlot': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePlot,
                    request_deserializer=plotter__pb2.PlotRequest.FromString,
                    response_serializer=plotter__pb2.PlotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plotter.PlotterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlotterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plotter.PlotterService/GeneratePlot',
            plotter__pb2.PlotRequest.SerializeToString,
            plotter__pb2.PlotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
