set dotenv-load := false
venv:
    if not exist venv ( python -m venv venv && .\venv\Scripts\activate && pip install -r requirements.dev.txt )

proto:
    python -m grpc_tools.protoc -I. --python_out=. --pyi_out=. --grpc_python_out=. user.proto

