set shell := ["cmd.exe", "/c"]

test:
    venv\Scripts\activate && python test_client.py

venv:
    venv\Scripts\activate

server:
    venv\Scripts\activate && python server.py
    

proto:
    python -m grpc_tools.protoc -I./proto --python_out=./proto --pyi_out=./proto --grpc_python_out=./proto ./proto/plotter.proto
    
